user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

serie:
    resource: "@SerieBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

app:
    resource: '@AppBundle/Controller/'
    type:     annotation

setLanguage:
    path:     /{language}
    defaults: { _controller: "SerieBundle:Default:language" }
