user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

serie:
    resource: "@SerieBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
