serie_season:
    resource: "@SerieBundle/Resources/config/routing/season.yml"
    prefix:   /season

serie_seriecomment:
    resource: "@SerieBundle/Resources/config/routing/seriecomment.yml"
    prefix:   /seriecomment

serie_addComment:
    pattern:  /comment/{serie_id}
    defaults: { _controller: SerieBundle:SerieComment:addComment }
    requirements:
        _method:  POST
        
serie_episode:
    resource: "@SerieBundle/Resources/config/routing/episode.yml"
    prefix:   /episode

serie_serie:
    resource: "@SerieBundle/Resources/config/routing/serie.yml"
    prefix:   /serie
    
serie_legalNotice:
    path:     /mentions-legales
    defaults: { _controller: SerieBundle:Default:legalNotice }
=======
serie_showCategories:
    path:     /genres
    defaults: { _controller: "SerieBundle:Default:categoryList" }

serie_showCategory:
    path:     /genres/{name}
    defaults: { _controller: "SerieBundle:Default:serieList" }

series_search:
    path:     /search
    defaults: { _controller: "SerieBundle:Default:globalSearch" }

serie_showSeason:
    path:     /serie/{name}/season/{id}
    defaults: { _controller: "SerieBundle:Season:showSeason" }
