serie_episode:
    resource: "@SerieBundle/Resources/config/routing/episode.yml"
    prefix:   /episode

serie_serie:
    resource: "@SerieBundle/Resources/config/routing/serie.yml"
    prefix:   /serie

serie_showCategories:
    path:     /genres
    defaults: { _controller: "SerieBundle:Default:categoryList" }

serie_showCategory:
    path:     /genres/{name}
    defaults: { _controller: "SerieBundle:Default:serieList" }

series_search:
    path:     /search
    defaults: { _controller: "SerieBundle:Default:globalSearch" }