episode_update:
    path:     /{id}/update
    defaults: { _controller: "SerieBundle:Episode:update" }
    methods:  [POST, PUT]

episode_delete:
    path:     /delete/{episodeId}
    defaults: { _controller: "SerieBundle:Episode:deleteEpisode" }
