season_update:
    path:     /{id}/update
    defaults: { _controller: "SerieBundle:Season:update" }
    methods:  [POST, PUT]

season_delete:
    path:     /delete/{seasonId}
    defaults: { _controller: "SerieBundle:Season:deleteSeason" }

