season_update:
    path:     /{serie_id}/{season_number}/update
    defaults: { _controller: "SerieBundle:Season:update" }
    methods:  [POST, PUT]

season_delete:
    path:     /delete/{seasonId}
    defaults: { _controller: "SerieBundle:Season:deleteSeason" }

