season:
    path:     /
    defaults: { _controller: "SerieBundle:Season:index" }

season_show:
    path:     /show/{id}
    defaults: { _controller: "SerieBundle:Season:show" }

season_new:
    path:     /new
    defaults: { _controller: "SerieBundle:Season:new" }

season_create:
    path:     /create
    defaults: { _controller: "SerieBundle:Season:create" }
    methods:  POST

season_edit:
    path:     /{id}/edit
    defaults: { _controller: "SerieBundle:Season:edit" }

season_update:
    path:     /{id}/update
    defaults: { _controller: "SerieBundle:Season:update" }
    methods:  [POST, PUT]

season_delete:
    path:     /{id}/delete
    defaults: { _controller: "SerieBundle:Season:delete" }
    methods:  [POST, DELETE]
