serie_new:
    path:     /newSerie
    defaults: { _controller: "SerieBundle:Serie:newSerie" }

serie_create:
    path:     /create
    defaults: { _controller: "SerieBundle:Serie:create" }
    methods:  POST

serie_edit:
    path:     /edit/{id}
    defaults: { _controller: "SerieBundle:Serie:editSerie" }

serie_update:
    path:     /update/{id}
    defaults: { _controller: "SerieBundle:Serie:update", id:0 }
    methods:  [POST, PUT]

serie_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:Serie:deleteSerie", id:0 }

serie_detail:
    path:     /{name}
    defaults:  { _controller: "SerieBundle:Serie:showSerieDetail"}

serie_showSeason:
    path:     /{name}/season/{id}
    defaults: { _controller: "SerieBundle:Season:showSeason" }

serie_addSeason:
    path:     /{name}/addSeason
    defaults: { _controller: "SerieBundle:Season:addSeason" }

serie_addEpisode:
    path:     /{serieName}/season/{seasonId}/addEpisode
    defaults: { _controller: "SerieBundle:Episode:addEpisode" }