serie_new:
    path:     /new/{id}
    defaults: { _controller: "SerieBundle:Serie:newSerie", id:0 }

serie_create:
    path:     /create
    defaults: { _controller: "SerieBundle:Serie:create" }
    methods:  POST

serie_edit:
    path:     /edit/{id}
    defaults: { _controller: "SerieBundle:Serie:editSerie", id:0 }

serie_update:
    path:     /update/{id}
    defaults: { _controller: "SerieBundle:Serie:update", id:0 }
    methods:  [POST, PUT]

serie_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:Serie:deleteSerie" }

serie_detail:
    path:     /{name}
    defaults:  { _controller: "SerieBundle:Serie:showSerieDetail"}
