serie_addSerie:
    path:     /addSerie
    defaults: { _controller: "SerieBundle:Serie:addSerie" }

serie_edit:
    path:     /edit/{id}
    defaults: { _controller: "SerieBundle:Serie:editSerie" }

serie_update:
    path:     /update/{id}
    defaults: { _controller: "SerieBundle:Serie:update", id:0 }
    methods:  [POST, PUT]

serie_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:Serie:deleteSerie" }

serie_detail:
    path:     /{name}
    defaults:  { _controller: "SerieBundle:Serie:showSerieDetail"}

serie_showSeason:
    path:     /{name}/season/{seasonNumber}
    defaults: { _controller: "SerieBundle:Season:showSeason" }

serie_addSeason:
    path:     /{name}/addSeason
    defaults: { _controller: "SerieBundle:Season:addSeason" }

serie_editSeason:
    path:     /{serieName}/season/{seasonNumber}/editSeason
    defaults: { _controller: "SerieBundle:Season:editSeason"}

serie_addEpisode:
    path:     /{serieName}/season/{seasonNumber}/addEpisode
    defaults: { _controller: "SerieBundle:Episode:addEpisode" }

serie_editEpisode:
    path:     /{serieName}/season/{seasonNumber}/episode/{episodeNumber}/editEpisode
    defaults: { _controller: "SerieBundle:Episode:editEpisode"}
