serie_new:
    path:     /new/{id}
    defaults: { _controller: "SerieBundle:Serie:new", id:0 }

serie_create:
    path:     /create
    defaults: { _controller: "SerieBundle:Serie:create" }
    methods:  POST

serie_edit:
    path:     /{id}/edit
    defaults: { _controller: "SerieBundle:Serie:edit" }

serie_update:
    path:     /{id}/update
    defaults: { _controller: "SerieBundle:Serie:update" }
    methods:  [POST, PUT]

serie_delete:
    path:     /delete/{id}
    defaults: { _controller: "SerieBundle:Serie:deleteSerie", id:0}

serie_detail:
    path:     /{name}
    defaults:  { _controller: "SerieBundle:Serie:showSerieDetail"}